name: skyformer

dependencies:
  - python=3.6
  - pytorch=1.8.0
  - transformers=4.5.0 -c conda-forge
  - datasets=1.5.0
  - einops -c conda-forge
  - pip:
      - performer-pytorch
      - local-attention
      - axial_positional_embedding
      - tensorboard==2.5.0
      - fsspec
      - wrapt
      - opt_einsum
      - gast
      - astunparse
      - psutil
