# @package _group_
defaults:
    - task: null
    - model: null
    - criterion: cross_entropy
    - optimizer: null
    - lr_scheduler: fixed
    - bpe: null
    - tokenizer: null
    - scoring: null
    - generation: null
    - common_eval: null
    - eval_lm: null
